/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    build: Build;
    product: Product;
    player: Player;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    build: BuildSelect<false> | BuildSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    player: PlayerSelect<false> | PlayerSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | FeatureCardBlock
    | FeatureListBlock
    | ApiCardListBlock
    | WhyWorkWithUsBlock
    | HeroMeteorBlock
    | Integration2Block
    | Feature242Block
    | Feature157Block
    | Feature251Block
    | {
        enabled?: boolean | null;
        title?: string | null;
        subtitle?: string | null;
        ratingText?: string | null;
        linkText?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          reference?: (string | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        testimonials?:
          | {
              name: string;
              role: string;
              content: string;
              avatar?: (string | null) | Media;
              rating?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonial19';
      }
    | {
        enabled?: boolean | null;
        title: string;
        description: string;
        buttonText: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          reference?: (string | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'feature253';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardBlock".
 */
export interface FeatureCardBlock {
  icon: 'star' | 'heart' | 'check' | 'lightning' | 'shield' | 'rocket';
  title: string;
  description: string;
  backgroundColor?: ('default' | 'primary' | 'secondary' | 'accent') | null;
  textAlignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureListBlock".
 */
export interface FeatureListBlock {
  title?: string | null;
  description?: string | null;
  layout?: ('grid' | 'list' | 'cards') | null;
  columns?: ('1' | '2' | '3' | '4') | null;
  features: {
    icon: 'star' | 'heart' | 'check' | 'lightning' | 'shield' | 'rocket' | 'settings' | 'users' | 'globe' | 'award';
    title: string;
    description: string;
    link?: {
      url?: string | null;
      text?: string | null;
    };
    id?: string | null;
  }[];
  backgroundColor?: ('default' | 'primary' | 'secondary' | 'accent' | 'muted') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApiCardListBlock".
 */
export interface ApiCardListBlock {
  title?: string | null;
  description?: string | null;
  cardType: 'product' | 'accessories' | 'builds';
  category_id?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8') | null;
  accessory_category?: ('' | '9' | '10' | '11' | '12' | '13' | '14') | null;
  build_type?: ('' | 'gaming' | 'office' | 'workstation' | 'budget' | 'high-end' | '--') | null;
  layout?: ('grid' | 'list' | 'carousel') | null;
  /**
   * Number of columns for grid layout
   */
  columns?: ('1' | '2' | '3' | '4') | null;
  /**
   * 0 = show all items
   */
  itemsPerPage?: number | null;
  showPagination?: boolean | null;
  styling?: {
    backgroundColor?: ('default' | 'primary' | 'secondary' | 'accent' | 'muted') | null;
    cardStyle?: ('default' | 'elevated' | 'bordered' | 'minimal') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'apiCardList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyWorkWithUsBlock".
 */
export interface WhyWorkWithUsBlock {
  /**
   * Main heading for the section
   */
  heading?: string | null;
  /**
   * Add reasons why customers should work with you
   */
  reasons?:
    | {
        /**
         * Short title for this reason
         */
        title: string;
        /**
         * Detailed description of this reason
         */
        description: string;
        /**
         * Choose an icon to represent this reason
         */
        icon:
          | 'GitPullRequest'
          | 'SquareKanban'
          | 'RadioTower'
          | 'WandSparkles'
          | 'Layers'
          | 'BatteryCharging'
          | 'Shield'
          | 'Zap'
          | 'CheckCircle'
          | 'Star';
        id?: string | null;
      }[]
    | null;
  /**
   * Number of columns for desktop layout
   */
  columns?: ('2' | '3' | '4') | null;
  /**
   * Background color for the section
   */
  backgroundColor?: ('default' | 'muted' | 'accent' | 'secondary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyWorkWithUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroMeteorBlock".
 */
export interface HeroMeteorBlock {
  subtitle?: string | null;
  title: string;
  buttonText?: string | null;
  /**
   * Toggle to show or hide the button link
   */
  showButton?: boolean | null;
  buttonLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  /**
   * Number of animated meteors (0 to disable)
   */
  meteorsCount?: number | null;
  showGlobe?: boolean | null;
  globeSize?: ('small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroMeteor';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Integration2Block".
 */
export interface Integration2Block {
  blockName?: string | null;
  title?: string | null;
  subtitle?: string | null;
  buttonLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockType: 'integration2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature242Block".
 */
export interface Feature242Block {
  blockName?: string | null;
  title?: string | null;
  description?: string | null;
  readMoreText?: string | null;
  items?:
    | {
        title: string;
        href?: string | null;
        image: string | Media;
        /**
         * Used if no media image is selected
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'feature242';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature157Block".
 */
export interface Feature157Block {
  blockName?: string | null;
  subtitle?: string | null;
  title?: string | null;
  /**
   * You must provide exactly 2 service cards
   */
  cards?:
    | {
        title: string;
        description: string;
        /**
         * Choose to link to an existing page or enter a custom URL. Leave empty to disable link functionality.
         */
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
        };
        image?: (string | null) | Media;
        /**
         * Used if no media image is selected
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'feature157';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature251Block".
 */
export interface Feature251Block {
  blockName?: string | null;
  card1?: {
    title?: string | null;
    enabled?: boolean | null;
    description?: string | null;
    icons?: {
      icon1?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
      icon2?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
      icon3?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
      icon4?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
    };
  };
  card2?: {
    title?: string | null;
    enabled?: boolean | null;
    description?: string | null;
    icons?: {
      topIcon?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
      bottomIcon?:
        | (
            | 'google'
            | 'figma'
            | 'notion'
            | 'g2'
            | 'block'
            | 'cpu'
            | 'gpu'
            | 'motherboard'
            | 'memory'
            | 'storage'
            | 'power-supply'
            | 'case'
            | 'cpu-cooler'
          )
        | null;
    };
  };
  card3?: {
    title?: string | null;
    enabled?: boolean | null;
    description?: string | null;
    image?:
      | (
          | 'google'
          | 'figma'
          | 'notion'
          | 'g2'
          | 'block'
          | 'cpu'
          | 'gpu'
          | 'motherboard'
          | 'memory'
          | 'storage'
          | 'power-supply'
          | 'case'
          | 'cpu-cooler'
        )
      | null;
  };
  card4?: {
    title?: string | null;
    enabled?: boolean | null;
    description?: string | null;
  };
  id?: string | null;
  blockType: 'feature251';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        featureCard?: T | FeatureCardBlockSelect<T>;
        featureList?: T | FeatureListBlockSelect<T>;
        apiCardList?: T | ApiCardListBlockSelect<T>;
        whyWorkWithUs?: T | WhyWorkWithUsBlockSelect<T>;
        heroMeteor?: T | HeroMeteorBlockSelect<T>;
        integration2?: T | Integration2BlockSelect<T>;
        feature242?: T | Feature242BlockSelect<T>;
        feature157?: T | Feature157BlockSelect<T>;
        feature251?: T | Feature251BlockSelect<T>;
        testimonial19?:
          | T
          | {
              enabled?: T;
              title?: T;
              subtitle?: T;
              ratingText?: T;
              linkText?: T;
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              testimonials?:
                | T
                | {
                    name?: T;
                    role?: T;
                    content?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        feature253?:
          | T
          | {
              enabled?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardBlock_select".
 */
export interface FeatureCardBlockSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  backgroundColor?: T;
  textAlignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureListBlock_select".
 */
export interface FeatureListBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  layout?: T;
  columns?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              url?: T;
              text?: T;
            };
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApiCardListBlock_select".
 */
export interface ApiCardListBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  cardType?: T;
  category_id?: T;
  accessory_category?: T;
  build_type?: T;
  layout?: T;
  columns?: T;
  itemsPerPage?: T;
  showPagination?: T;
  styling?:
    | T
    | {
        backgroundColor?: T;
        cardStyle?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyWorkWithUsBlock_select".
 */
export interface WhyWorkWithUsBlockSelect<T extends boolean = true> {
  heading?: T;
  reasons?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  columns?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroMeteorBlock_select".
 */
export interface HeroMeteorBlockSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  buttonText?: T;
  showButton?: T;
  buttonLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  meteorsCount?: T;
  showGlobe?: T;
  globeSize?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Integration2Block_select".
 */
export interface Integration2BlockSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  subtitle?: T;
  buttonLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature242Block_select".
 */
export interface Feature242BlockSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  description?: T;
  readMoreText?: T;
  items?:
    | T
    | {
        title?: T;
        href?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature157Block_select".
 */
export interface Feature157BlockSelect<T extends boolean = true> {
  blockName?: T;
  subtitle?: T;
  title?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Feature251Block_select".
 */
export interface Feature251BlockSelect<T extends boolean = true> {
  blockName?: T;
  card1?:
    | T
    | {
        title?: T;
        enabled?: T;
        description?: T;
        icons?:
          | T
          | {
              icon1?: T;
              icon2?: T;
              icon3?: T;
              icon4?: T;
            };
      };
  card2?:
    | T
    | {
        title?: T;
        enabled?: T;
        description?: T;
        icons?:
          | T
          | {
              topIcon?: T;
              bottomIcon?: T;
            };
      };
  card3?:
    | T
    | {
        title?: T;
        enabled?: T;
        description?: T;
        image?: T;
      };
  card4?:
    | T
    | {
        title?: T;
        enabled?: T;
        description?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Main heading text for the hero section
   */
  headerHeading?: string | null;
  /**
   * Description text below the heading
   */
  headerDescription?: string | null;
  /**
   * Toggle visibility of the hero section
   */
  showHero?: boolean | null;
  navItems?:
    | {
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global settings for build pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build".
 */
export interface Build {
  id: string;
  blocks?: (BuildInfo | BuildComponents)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildInfo".
 */
export interface BuildInfo {
  heading?: string | null;
  description?: string | null;
  /**
   * Show build type
   */
  showBuildType?: boolean | null;
  /**
   * Show build price
   */
  showPrice?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buildInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildComponents".
 */
export interface BuildComponents {
  heading?: string | null;
  /**
   * Show list of components in this build
   */
  showComponentList?: boolean | null;
  /**
   * Show component prices
   */
  showPrices?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buildComponents';
}
/**
 * Global settings for product pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: string;
  blocks?: (ProductInfo | ProductReviews | ProductAttributes)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductInfo".
 */
export interface ProductInfo {
  heading?: string | null;
  description?: string | null;
  /**
   * Show product category
   */
  showCategory?: boolean | null;
  /**
   * Show product price
   */
  showPrice?: boolean | null;
  /**
   * Show stock status
   */
  showStock?: boolean | null;
  /**
   * Show product image
   */
  showImage?: boolean | null;
  /**
   * Show Amazon button
   */
  showButtonAmazon?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductReviews".
 */
export interface ProductReviews {
  heading?: string | null;
  /**
   * Show product reviews
   */
  showReviews?: boolean | null;
  /**
   * Show average rating
   */
  showRating?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productReviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductAttributes".
 */
export interface ProductAttributes {
  heading?: string | null;
  /**
   * Show brand
   */
  showBrand?: boolean | null;
  /**
   * Show model
   */
  showModel?: boolean | null;
  /**
   * Show color
   */
  showColor?: boolean | null;
  /**
   * Show cores
   */
  showCores?: boolean | null;
  /**
   * Show threads
   */
  showThreads?: boolean | null;
  /**
   * Show socket type
   */
  showSocketType?: boolean | null;
  /**
   * Show base speed
   */
  showBaseSpeed?: boolean | null;
  /**
   * Show turbo speed
   */
  showTurboSpeed?: boolean | null;
  /**
   * Show architecture
   */
  showArchitecture?: boolean | null;
  /**
   * Show core family
   */
  showCoreFamily?: boolean | null;
  /**
   * Show generation
   */
  showGeneration?: boolean | null;
  /**
   * Show integrated graphics
   */
  showIntegratedGraphics?: boolean | null;
  /**
   * Show memory speed
   */
  showMemorySpeed?: boolean | null;
  /**
   * Show series
   */
  showSeries?: boolean | null;
  /**
   * Show base fan RPM
   */
  showBaseFanRPM?: boolean | null;
  /**
   * Show max fan RPM
   */
  showMaxFanRPM?: boolean | null;
  /**
   * Show base noise level
   */
  showBaseNoiseLevel?: boolean | null;
  /**
   * Show max noise level
   */
  showMaxNoiseLevel?: boolean | null;
  /**
   * Show base clock
   */
  showBaseClock?: boolean | null;
  /**
   * Show chipset
   */
  showChipset?: boolean | null;
  /**
   * Show clock speed
   */
  showClockSpeed?: boolean | null;
  /**
   * Show frame sync
   */
  showFrameSync?: boolean | null;
  /**
   * Show interface
   */
  showInterface?: boolean | null;
  /**
   * Show length
   */
  showLength?: boolean | null;
  /**
   * Show memory interface
   */
  showMemoryInterface?: boolean | null;
  /**
   * Show memory
   */
  showMemory?: boolean | null;
  /**
   * Show form factor
   */
  showFormFactor?: boolean | null;
  /**
   * Show max RAM support
   */
  showMaxRAMSupport?: boolean | null;
  /**
   * Show RAM slots
   */
  showRAMSlots?: boolean | null;
  /**
   * Show CAS latency
   */
  showCASLatency?: boolean | null;
  /**
   * Show one unit memory
   */
  showOneUnitMemory?: boolean | null;
  /**
   * Show quantity
   */
  showQuantity?: boolean | null;
  /**
   * Show RAM speed
   */
  showRAMSpeed?: boolean | null;
  /**
   * Show RAM type
   */
  showRAMType?: boolean | null;
  /**
   * Show total memory
   */
  showTotalMemory?: boolean | null;
  /**
   * Show cache memory
   */
  showCacheMemory?: boolean | null;
  /**
   * Show capacity
   */
  showCapacity?: boolean | null;
  /**
   * Show memory type
   */
  showMemoryType?: boolean | null;
  /**
   * Show efficiency
   */
  showEfficiency?: boolean | null;
  /**
   * Show power
   */
  showPower?: boolean | null;
  /**
   * Show cabinet type
   */
  showCabinetType?: boolean | null;
  /**
   * Show side panel
   */
  showSidePanel?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productAttributes';
}
/**
 * Global settings for player pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player".
 */
export interface Player {
  id: string;
  blocks?: (PlayerInfo | SkinsComponents | GearComponents | PCSpecs | SetupStreaming)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlayerInfo".
 */
export interface PlayerInfo {
  id?: string | null;
  blockName?: string | null;
  blockType: 'playerInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkinsComponents".
 */
export interface SkinsComponents {
  id?: string | null;
  blockName?: string | null;
  blockType: 'skinsComponents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GearComponents".
 */
export interface GearComponents {
  id?: string | null;
  blockName?: string | null;
  blockType: 'gearComponents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PCSpecs".
 */
export interface PCSpecs {
  id?: string | null;
  blockName?: string | null;
  blockType: 'pcSpecs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SetupStreaming".
 */
export interface SetupStreaming {
  id?: string | null;
  blockName?: string | null;
  blockType: 'setupStreaming';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  headerHeading?: T;
  headerDescription?: T;
  showHero?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build_select".
 */
export interface BuildSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        buildInfo?: T | BuildInfoSelect<T>;
        buildComponents?: T | BuildComponentsSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildInfo_select".
 */
export interface BuildInfoSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  showBuildType?: T;
  showPrice?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildComponents_select".
 */
export interface BuildComponentsSelect<T extends boolean = true> {
  heading?: T;
  showComponentList?: T;
  showPrices?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        productInfo?: T | ProductInfoSelect<T>;
        productReviews?: T | ProductReviewsSelect<T>;
        productAttributes?: T | ProductAttributesSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductInfo_select".
 */
export interface ProductInfoSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  showCategory?: T;
  showPrice?: T;
  showStock?: T;
  showImage?: T;
  showButtonAmazon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductReviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  heading?: T;
  showReviews?: T;
  showRating?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductAttributes_select".
 */
export interface ProductAttributesSelect<T extends boolean = true> {
  heading?: T;
  showBrand?: T;
  showModel?: T;
  showColor?: T;
  showCores?: T;
  showThreads?: T;
  showSocketType?: T;
  showBaseSpeed?: T;
  showTurboSpeed?: T;
  showArchitecture?: T;
  showCoreFamily?: T;
  showGeneration?: T;
  showIntegratedGraphics?: T;
  showMemorySpeed?: T;
  showSeries?: T;
  showBaseFanRPM?: T;
  showMaxFanRPM?: T;
  showBaseNoiseLevel?: T;
  showMaxNoiseLevel?: T;
  showBaseClock?: T;
  showChipset?: T;
  showClockSpeed?: T;
  showFrameSync?: T;
  showInterface?: T;
  showLength?: T;
  showMemoryInterface?: T;
  showMemory?: T;
  showFormFactor?: T;
  showMaxRAMSupport?: T;
  showRAMSlots?: T;
  showCASLatency?: T;
  showOneUnitMemory?: T;
  showQuantity?: T;
  showRAMSpeed?: T;
  showRAMType?: T;
  showTotalMemory?: T;
  showCacheMemory?: T;
  showCapacity?: T;
  showMemoryType?: T;
  showEfficiency?: T;
  showPower?: T;
  showCabinetType?: T;
  showSidePanel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player_select".
 */
export interface PlayerSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        playerInfo?: T | PlayerInfoSelect<T>;
        skinsComponents?: T | SkinsComponentsSelect<T>;
        gearComponents?: T | GearComponentsSelect<T>;
        pcSpecs?: T | PCSpecsSelect<T>;
        setupStreaming?: T | SetupStreamingSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlayerInfo_select".
 */
export interface PlayerInfoSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkinsComponents_select".
 */
export interface SkinsComponentsSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GearComponents_select".
 */
export interface GearComponentsSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PCSpecs_select".
 */
export interface PCSpecsSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SetupStreaming_select".
 */
export interface SetupStreamingSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}