volumes:
  postgres_data: {}
  mongo_data: {}

networks:
  internal: {}
  external:
    driver: bridge

services:
  postgres:
    image: postgres:17.2-alpine3.21
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: "${POSTGRES__DB}"
      POSTGRES_USER: "${POSTGRES__USER}"
      POSTGRES_PASSWORD: "${POSTGRES__PASSWORD}"
    expose:
      - ${POSTGRES__PORT}
    ports:
      - "${POSTGRES__PORT}:5432"
    networks:
      - internal
      - external
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${POSTGRES__USER} --dbname ${POSTGRES__DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    networks:
      - internal
      - external
    volumes:
      - mongo_data:/var/lib/mongo/data:rw
    expose:
      - ${MONGO__PORT}
    ports:
      - "${MONGO__PORT}:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO__DB}

      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - external
