"""add stickers tables

Revision ID: 01b805f35e0d
Revises: 2e3ef2df6a26
Create Date: 2025-08-19 09:37:22.934433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b805f35e0d'
down_revision: Union[str, None] = '2e3ef2df6a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('tournire', sa.String(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('s_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stickers_id'), 'stickers', ['id'], unique=False)
    op.create_table('teamstickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('stickers_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stickers_id'], ['stickers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamstickers_id'), 'teamstickers', ['id'], unique=False)
    op.create_table('playerstickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('stickers_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['stickers_id'], ['stickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstickers_id'), 'playerstickers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerstickers_id'), table_name='playerstickers')
    op.drop_table('playerstickers')
    op.drop_index(op.f('ix_teamstickers_id'), table_name='teamstickers')
    op.drop_table('teamstickers')
    op.drop_index(op.f('ix_stickers_id'), table_name='stickers')
    op.drop_table('stickers')
    # ### end Alembic commands ###
