"""add skins params

Revision ID: 1c7b27b5498e
Revises: 9d259877c4cd
Create Date: 2025-08-05 14:23:20.263042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7b27b5498e'
down_revision: Union[str, None] = '9d259877c4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_skins', sa.Column('is_stat_track', sa.Boolean(), nullable=True))
    op.add_column('player_skins', sa.Column('wear_level', sa.String(), nullable=True))
    op.add_column('player_skins', sa.Column('is_wear_level_track', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_skins', 'is_wear_level_track')
    op.drop_column('player_skins', 'wear_level')
    op.drop_column('player_skins', 'is_stat_track')
    # ### end Alembic commands ###
