"""add show on site flag to build model

Revision ID: 29f080d6b9e4
Revises: 98496de0d992
Create Date: 2025-07-14 10:49:34.457947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f080d6b9e4'
down_revision: Union[str, None] = '98496de0d992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('show_in_site', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'show_in_site')
    # ### end Alembic commands ###
