"""update games 

Revision ID: 2e3ef2df6a26
Revises: 5edb61719140
Create Date: 2025-08-18 14:02:31.656134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3ef2df6a26'
down_revision: Union[str, None] = '5edb61719140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('games', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('games', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
