"""empty message

Revision ID: 3a2295282ad8
Revises: d66d98e6e73b
Create Date: 2025-07-29 12:10:58.019859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2295282ad8'
down_revision: Union[str, None] = 'd66d98e6e73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameraattributes',
    sa.Column('photo_sensor_technology', sa.String(), nullable=True),
    sa.Column('video_capture_resolution', sa.Integer(), nullable=True),
    sa.Column('maximum_aperture', sa.Float(), nullable=True),
    sa.Column('flash_memory_type', sa.Integer(), nullable=True),
    sa.Column('video_capture_format', sa.String(), nullable=True),
    sa.Column('supported_audio_format', sa.String(), nullable=True),
    sa.Column('screen_size', sa.Float(), nullable=True),
    sa.Column('connectivity_technology', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_cameraattributes_id'), 'cameraattributes', ['id'], unique=False)
    op.create_table('headphonesattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('ear_placement', sa.String(), nullable=True),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.Column('impedance', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_headphonesattributes_id'), 'headphonesattributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headphonesattributes_id'), table_name='headphonesattributes')
    op.drop_table('headphonesattributes')
    op.drop_index(op.f('ix_cameraattributes_id'), table_name='cameraattributes')
    op.drop_table('cameraattributes')
    # ### end Alembic commands ###
