"""fix_skin_autoincrement

Revision ID: 416cf53029ae
Revises: 7bea9fe84998
Create Date: 2025-07-24 14:13:27.070386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416cf53029ae'
down_revision: Union[str, None] = '7bea9fe84998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Fix sequence for skin table
    op.execute("SELECT setval('skin_id_seq', (SELECT MAX(id) FROM skin))")
    
    # Fix sequence for skincategory table
    op.execute("SELECT setval('skincategory_id_seq', (SELECT MAX(id) FROM skincategory))")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
