"""add custom droduct relaton

Revision ID: 6d7b5208cca5
Revises: d71a0b5d0a8e
Create Date: 2025-08-13 12:07:53.119593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7b5208cca5'
down_revision: Union[str, None] = 'd71a0b5d0a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_product_reletion', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key(None, 'custom_product_reletion', 'player', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_product_reletion', type_='foreignkey')
    op.alter_column('custom_product_reletion', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
