"""add team 

Revision ID: 7b6df93bdcbb
Revises: bd180a393be9
Create Date: 2025-08-15 14:21:08.543579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6df93bdcbb'
down_revision: Union[str, None] = 'bd180a393be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('jerseys_img', sa.String(), nullable=True),
    sa.Column('socila_media_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.add_column('player', sa.Column('team_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('fk_player_country'), 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'countries', ['country'], ['id'])
    op.create_foreign_key(None, 'player', 'teams', ['team_id'], ['id'])
    op.drop_column('player', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_country'), 'player', 'countries', ['country'], ['id'], ondelete='SET NULL')
    op.drop_column('player', 'team_id')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
