"""add_skins_tables

Revision ID: 7bea9fe84998
Revises: eb92576b5b87
Create Date: 2025-07-24 10:40:27.188536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bea9fe84998'
down_revision: Union[str, None] = 'eb92576b5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skincategory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skincategory_id'), 'skincategory', ['id'], unique=False)
    op.create_table('skin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('weapon', sa.String(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skincategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_id'), 'skin', ['id'], unique=False)
    # op.drop_table('product_old')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('product_old',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('asin', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    # sa.Column('low_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('high_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('--', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('product_category_id_fkey'), ondelete='SET NULL')
    # )
    op.drop_index(op.f('ix_skin_id'), table_name='skin')
    op.drop_table('skin')
    op.drop_index(op.f('ix_skincategory_id'), table_name='skincategory')
    op.drop_table('skincategory')
    # ### end Alembic commands ###
