"""add_build_table

Revision ID: 837604087cdb
Revises: d086d6eddddf
Create Date: 2025-06-26 14:17:02.126423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837604087cdb'
down_revision: Union[str, None] = 'd086d6eddddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('build_price', sa.Float(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('cpu_cooler_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('motherboard_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('psu_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cpu_cooler_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cpu_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gpu_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motherboard_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['psu_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ram_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_id'), 'build', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_id'), table_name='build')
    op.drop_table('build')
    # ### end Alembic commands ###
