"""add_build_type_column

Revision ID: 962609c65729
Revises: 837604087cdb
Create Date: 2025-06-27 11:49:30.025730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962609c65729'
down_revision: Union[str, None] = '837604087cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('build_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'build_type')
    # ### end Alembic commands ###
