"""add image urls fields to product model

Revision ID: 98496de0d992
Revises: cb602caf2029
Create Date: 2025-07-11 16:15:57.904321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98496de0d992'
down_revision: Union[str, None] = 'cb602caf2029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('low_image_url', sa.String(), nullable=True))
    op.add_column('product', sa.Column('high_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'high_image_url')
    op.drop_column('product', 'low_image_url')
    # ### end Alembic commands ###
