"""add file table

Revision ID: 990f6eeb69e1
Revises: 9c96f8db6d7d
Create Date: 2025-08-14 12:18:15.939700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990f6eeb69e1'
down_revision: Union[str, None] = '9c96f8db6d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_s3file_id'), 's3file', ['id'], unique=False)
    op.create_index(op.f('ix_s3file_key'), 's3file', ['key'], unique=True)
    op.drop_constraint(op.f('custom_product_reletion_user_id_fkey'), 'custom_product_reletion', type_='foreignkey')
    op.create_foreign_key(None, 'custom_product_reletion', 'player', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_product_reletion', type_='foreignkey')
    op.create_foreign_key(op.f('custom_product_reletion_user_id_fkey'), 'custom_product_reletion', 'player', ['user_id'], ['id'])
    op.drop_index(op.f('ix_s3file_key'), table_name='s3file')
    op.drop_index(op.f('ix_s3file_id'), table_name='s3file')
    op.drop_table('s3file')
    # ### end Alembic commands ###
