"""add image urls

Revision ID: 9c96f8db6d7d
Revises: b5b9287da6e1
Create Date: 2025-08-14 11:14:30.623312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c96f8db6d7d'
down_revision: Union[str, None] = 'b5b9287da6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_product_reletion', sa.Column('low_image_url', sa.String(), nullable=True))
    op.add_column('custom_product_reletion', sa.Column('high_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_product_reletion', 'high_image_url')
    op.drop_column('custom_product_reletion', 'low_image_url')
    # ### end Alembic commands ###
