"""rename_camera_id_to_webcam_id_in_setupstreaminglist

Revision ID: 9d259877c4cd
Revises: 63fa87902c6d
Create Date: 2025-07-30 17:58:00.220075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d259877c4cd'
down_revision: Union[str, None] = '63fa87902c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setupstreaminglist', 'camera_id',
               new_column_name='webcam_id',
               existing_type=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setupstreaminglist', 'webcam_id',
               new_column_name='camera_id',
               existing_type=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###
