"""add player note

Revision ID: a9478c66eeab
Revises: d3d30fcaa162
Create Date: 2025-08-08 10:56:21.742951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9478c66eeab'
down_revision: Union[str, None] = 'd3d30fcaa162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'note')
    # ### end Alembic commands ###
