"""add_player_tables

Revision ID: abc6eae892cd
Revises: bbc9985e983a
Create Date: 2025-07-25 11:22:13.606850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc6eae892cd'
down_revision: Union[str, None] = 'bbc9985e983a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gearlist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.BigInteger(), nullable=True),
    sa.Column('mouse_id', sa.BigInteger(), nullable=True),
    sa.Column('keyboard_id', sa.BigInteger(), nullable=True),
    sa.Column('headset_id', sa.BigInteger(), nullable=True),
    sa.Column('mousepad_id', sa.BigInteger(), nullable=True),
    sa.Column('earphones_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['earphones_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['headset_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['keyboard_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['mouse_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['mousepad_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gearlist_id'), 'gearlist', ['id'], unique=False)
    op.create_table('pcspecslist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cpu_id', sa.BigInteger(), nullable=True),
    sa.Column('cpu_cooler_id', sa.BigInteger(), nullable=True),
    sa.Column('gpu_id', sa.BigInteger(), nullable=True),
    sa.Column('motherboard_id', sa.BigInteger(), nullable=True),
    sa.Column('ram_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_id', sa.BigInteger(), nullable=True),
    sa.Column('power_supply_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['cpu_cooler_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['motherboard_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['power_supply_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcspecslist_id'), 'pcspecslist', ['id'], unique=False)
    op.create_table('setupstreaminglist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chair_id', sa.BigInteger(), nullable=True),
    sa.Column('microphone_id', sa.BigInteger(), nullable=True),
    sa.Column('webcam_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chair_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['microphone_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['webcam_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setupstreaminglist_id'), 'setupstreaminglist', ['id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_img', sa.Text(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('gear_list_id', sa.BigInteger(), nullable=True),
    sa.Column('pc_specs_list_id', sa.BigInteger(), nullable=True),
    sa.Column('setup_streaming_list_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['gear_list_id'], ['gearlist.id'], ),
    sa.ForeignKeyConstraint(['pc_specs_list_id'], ['pcspecslist.id'], ),
    sa.ForeignKeyConstraint(['setup_streaming_list_id'], ['setupstreaminglist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('player_skins',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('skin_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skin.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'skin_id')
    )
    op.drop_index(op.f('ix_product_asin_trgm'), table_name='product', postgresql_using='gin')
    op.drop_index(op.f('ix_product_title_trgm'), table_name='product', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_title_trgm'), 'product', [sa.literal_column('lower(title::text)')], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_product_asin_trgm'), 'product', [sa.literal_column('lower(asin::text)')], unique=False, postgresql_using='gin')
    op.drop_table('player_skins')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_setupstreaminglist_id'), table_name='setupstreaminglist')
    op.drop_table('setupstreaminglist')
    op.drop_index(op.f('ix_pcspecslist_id'), table_name='pcspecslist')
    op.drop_table('pcspecslist')
    op.drop_index(op.f('ix_gearlist_id'), table_name='gearlist')
    op.drop_table('gearlist')
    # ### end Alembic commands ###
