"""add display_name column to product table

Revision ID: add_display_name_to_product
Revises: bbc9985e983a
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_display_name_to_product'
down_revision: Union[str, None] = 'bbc9985e983a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add display_name column to product table
    op.add_column('product', sa.Column('display_name', sa.String(), nullable=True))
    
    # Update display_name for all products based on their attributes
    # CPU attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(cpuattributes.brand, ' ', cpuattributes.model)
        FROM cpuattributes 
        WHERE product.id = cpuattributes.product_id 
        AND cpuattributes.brand IS NOT NULL 
        AND cpuattributes.model IS NOT NULL
    """)
    
    # CPU Cooler attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(cpucoolerattributes.brand, ' ', cpucoolerattributes.model)
        FROM cpucoolerattributes 
        WHERE product.id = cpucoolerattributes.product_id 
        AND cpucoolerattributes.brand IS NOT NULL 
        AND cpucoolerattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # GPU attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(gpuattributes.brand, ' ', gpuattributes.model)
        FROM gpuattributes 
        WHERE product.id = gpuattributes.product_id 
        AND gpuattributes.brand IS NOT NULL 
        AND gpuattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Motherboard attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(motherboardattributes.brand, ' ', motherboardattributes.model)
        FROM motherboardattributes 
        WHERE product.id = motherboardattributes.product_id 
        AND motherboardattributes.brand IS NOT NULL 
        AND motherboardattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # RAM attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(ramattributes.brand, ' ', ramattributes.model)
        FROM ramattributes 
        WHERE product.id = ramattributes.product_id 
        AND ramattributes.brand IS NOT NULL 
        AND ramattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Storage attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(storageattributes.brand, ' ', storageattributes.model)
        FROM storageattributes 
        WHERE product.id = storageattributes.product_id 
        AND storageattributes.brand IS NOT NULL 
        AND storageattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Power Supply attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(powersupplyattributes.brand, ' ', powersupplyattributes.model)
        FROM powersupplyattributes 
        WHERE product.id = powersupplyattributes.product_id 
        AND powersupplyattributes.brand IS NOT NULL 
        AND powersupplyattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Case attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(caseattributes.brand, ' ', caseattributes.model)
        FROM caseattributes 
        WHERE product.id = caseattributes.product_id 
        AND caseattributes.brand IS NOT NULL 
        AND caseattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Mouse attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(mouseattributes.brand, ' ', mouseattributes.model)
        FROM mouseattributes 
        WHERE product.id = mouseattributes.product_id 
        AND mouseattributes.brand IS NOT NULL 
        AND mouseattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Monitor attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(monitorattributes.brand, ' ', monitorattributes.model)
        FROM monitorattributes 
        WHERE product.id = monitorattributes.product_id 
        AND monitorattributes.brand IS NOT NULL 
        AND monitorattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Keyboard attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(keyboardattributes.brand, ' ', keyboardattributes.model)
        FROM keyboardattributes 
        WHERE product.id = keyboardattributes.product_id 
        AND keyboardattributes.brand IS NOT NULL 
        AND keyboardattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Headset attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(headsetattributes.brand, ' ', headsetattributes.model)
        FROM headsetattributes 
        WHERE product.id = headsetattributes.product_id 
        AND headsetattributes.brand IS NOT NULL 
        AND headsetattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Mousepad attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(mousepadattributes.brand, ' ', mousepadattributes.model)
        FROM mousepadattributes 
        WHERE product.id = mousepadattributes.product_id 
        AND mousepadattributes.brand IS NOT NULL 
        AND mousepadattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # Chair attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(chairattributes.brand, ' ', chairattributes.model)
        FROM chairattributes 
        WHERE product.id = chairattributes.product_id 
        AND chairattributes.brand IS NOT NULL 
        AND chairattributes.model IS NOT NULL
        AND product.display_name IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'display_name')
    # ### end Alembic commands ### 