"""add origenal name 

Revision ID: b5b9287da6e1
Revises: 6d7b5208cca5
Create Date: 2025-08-13 14:53:12.677683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b9287da6e1'
down_revision: Union[str, None] = '6d7b5208cca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_product_reletion', sa.Column('original_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_product_reletion', 'original_name')
    # ### end Alembic commands ###
