"""create_index_oroduct

Revision ID: bbc9985e983a
Revises: 416cf53029ae
Create Date: 2025-07-24 17:47:33.631782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc9985e983a'
down_revision: Union[str, None] = '416cf53029ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension if not exists
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE INDEX ix_product_asin_trgm ON product USING gin (lower(asin) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_product_title_trgm ON product USING gin (lower(title) gin_trgm_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_product_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_product_asin_trgm")
    # ### end Alembic commands ###
