"""empty message

Revision ID: c02659db6c88
Revises: update_existing_display_names
Create Date: 2025-07-29 12:01:44.660549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02659db6c88'
down_revision: Union[str, None] = 'update_existing_display_names'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microphoneattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('product_dimensions', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('back_style', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_microphoneattributes_id'), 'microphoneattributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microphoneattributes_id'), table_name='microphoneattributes')
    op.drop_table('microphoneattributes')
    # ### end Alembic commands ###
