"""Add server_default to datetime columns

Revision ID: cb602caf2029
Revises: 962609c65729
Create Date: 2025-07-01 18:18:19.665861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb602caf2029'
down_revision: Union[str, None] = '962609c65729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server_default to product table datetime columns
    op.alter_column('product', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text("timezone('UTC', now())"),
                    nullable=False)
    op.alter_column('product', 'updated_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text("timezone('UTC', now())"),
                    server_onupdate=sa.text("timezone('UTC', now())"),
                    nullable=False)
    
    # Add server_default to build table datetime columns
    op.alter_column('build', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text("timezone('UTC', now())"),
                    nullable=False)
    op.alter_column('build', 'updated_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text("timezone('UTC', now())"),
                    server_onupdate=sa.text("timezone('UTC', now())"),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server_default from build table datetime columns
    op.alter_column('build', 'updated_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    server_onupdate=None,
                    nullable=False)
    op.alter_column('build', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    nullable=False)
    
    # Remove server_default from product table datetime columns
    op.alter_column('product', 'updated_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    server_onupdate=None,
                    nullable=False)
    op.alter_column('product', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    nullable=False)
    # ### end Alembic commands ###
