"""empty message

Revision ID: d086d6eddddf
Revises: 249698674045
Create Date: 2025-06-26 11:27:08.180101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd086d6eddddf'
down_revision: Union[str, None] = '249698674045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_keepa_id_key'), 'category', type_='unique')
    op.drop_column('category', 'keepa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('keepa_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('category_keepa_id_key'), 'category', ['keepa_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
