"""empty message

Revision ID: d0ed11b86de3
Revises: 3a2295282ad8
Create Date: 2025-07-29 15:43:30.365831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ed11b86de3'
down_revision: Union[str, None] = '3a2295282ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('product_target')
    op.create_foreign_key(None, 'caseattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cpuattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cpucoolerattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gpuattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'powersupplyattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ramattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'storageattributes', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storageattributes', type_='foreignkey')
    op.drop_constraint(None, 'ramattributes', type_='foreignkey')
    op.drop_constraint(None, 'powersupplyattributes', type_='foreignkey')
    op.drop_constraint(None, 'gpuattributes', type_='foreignkey')
    op.drop_constraint(None, 'cpucoolerattributes', type_='foreignkey')
    op.drop_constraint(None, 'cpuattributes', type_='foreignkey')
    op.drop_constraint(None, 'caseattributes', type_='foreignkey')
    # op.create_table('product_target',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('asin', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    # sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    # sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    # sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    # sa.Column('low_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('high_image_url', sa.TEXT(), autoincrement=False, nullable=True)
    # )
    # ### end Alembic commands ###
