"""rm weater level treak

Revision ID: d3d30fcaa162
Revises: d674324c00dd
Create Date: 2025-08-08 10:46:05.643827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d30fcaa162'
down_revision: Union[str, None] = 'd674324c00dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_skins', 'is_wear_level_track')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_skins', sa.Column('is_wear_level_track', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
