"""empty message

Revision ID: d66d98e6e73b
Revises: c02659db6c88
Create Date: 2025-07-29 12:06:42.473262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66d98e6e73b'
down_revision: Union[str, None] = 'c02659db6c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microphoneattributes', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('connectivity_technology', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('connector_type', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('special_feature', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('compatible_devices', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('colour', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('included_components', sa.String(), nullable=True))
    op.add_column('microphoneattributes', sa.Column('polar_pattern', sa.String(), nullable=True))
    op.drop_column('microphoneattributes', 'size')
    op.drop_column('microphoneattributes', 'product_dimensions')
    op.drop_column('microphoneattributes', 'back_style')
    op.drop_column('microphoneattributes', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microphoneattributes', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphoneattributes', sa.Column('back_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphoneattributes', sa.Column('product_dimensions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphoneattributes', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('microphoneattributes', 'polar_pattern')
    op.drop_column('microphoneattributes', 'included_components')
    op.drop_column('microphoneattributes', 'colour')
    op.drop_column('microphoneattributes', 'compatible_devices')
    op.drop_column('microphoneattributes', 'special_feature')
    op.drop_column('microphoneattributes', 'connector_type')
    op.drop_column('microphoneattributes', 'connectivity_technology')
    op.drop_column('microphoneattributes', 'model_name')
    # ### end Alembic commands ###
