"""add sovenir and oattern

Revision ID: d674324c00dd
Revises: 74b1bd06fc45
Create Date: 2025-08-07 14:16:12.590134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd674324c00dd'
down_revision: Union[str, None] = '74b1bd06fc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_skins', sa.Column('pattern', sa.BigInteger(), nullable=True))
    op.add_column('player_skins', sa.Column('souvenir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_skins', 'souvenir')
    op.drop_column('player_skins', 'pattern')
    # ### end Alembic commands ###
