"""add custom products

Revision ID: d71a0b5d0a8e
Revises: e956b95b3dd3
Create Date: 2025-08-13 10:26:42.382729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71a0b5d0a8e'
down_revision: Union[str, None] = 'e956b95b3dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_product_reletion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(), nullable=False),
    sa.Column('pozition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_product_reletion_id'), 'custom_product_reletion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_product_reletion_id'), table_name='custom_product_reletion')
    op.drop_table('custom_product_reletion')
    # ### end Alembic commands ###
