"""add image params in user

Revision ID: dbcbf0b2ff1a
Revises: 990f6eeb69e1
Create Date: 2025-08-14 15:18:40.479679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcbf0b2ff1a'
down_revision: Union[str, None] = '990f6eeb69e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('pc_image', sa.Text(), nullable=True))
    op.add_column('player', sa.Column('pc_image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'pc_image_name')
    op.drop_column('player', 'pc_image')
    # ### end Alembic commands ###
