"""add user links

Revision ID: e956b95b3dd3
Revises: a9478c66eeab
Create Date: 2025-08-11 13:50:44.369342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e956b95b3dd3'
down_revision: Union[str, None] = 'a9478c66eeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('user_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'user_urls')
    # ### end Alembic commands ###
