"""add build cost field

Revision ID: eb92576b5b87
Revises: 29f080d6b9e4
Create Date: 2025-07-14 12:30:11.136463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb92576b5b87'
down_revision: Union[str, None] = '29f080d6b9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('build_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'build_cost')
    # ### end Alembic commands ###
