"""add_mouse_attributes_table

Revision ID: fc85e03ac9c5
Revises: d0ed11b86de3
Create Date: 2025-07-30 10:58:40.845489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc85e03ac9c5'
down_revision: Union[str, None] = 'bbc9985e983a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chairattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('product_dimensions', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('back_style', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_chairattributes_id'), 'chairattributes', ['id'], unique=False)
    op.create_table('headsetattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('par_placement', sa.String(), nullable=True),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.Column('impedance', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_headsetattributes_id'), 'headsetattributes', ['id'], unique=False)
    op.create_table('keyboardattributes',
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('compatible_devices', sa.String(), nullable=True),
    sa.Column('connectivity_technology', sa.String(), nullable=True),
    sa.Column('keyboard_description', sa.String(), nullable=True),
    sa.Column('recommended_uses_for_product', sa.String(), nullable=True),
    sa.Column('special_feature', sa.String(), nullable=True),
    sa.Column('number_of_keys', sa.Integer(), nullable=True),
    sa.Column('keyboard_backlighting_color_support', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_keyboardattributes_id'), 'keyboardattributes', ['id'], unique=False)
    op.create_table('monitorattributes',
    sa.Column('screen_size', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('screen_surface_description', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_monitorattributes_id'), 'monitorattributes', ['id'], unique=False)
    op.create_table('mouseattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('connectivity_technology', sa.String(), nullable=True),
    sa.Column('special_feature', sa.String(), nullable=True),
    sa.Column('movement_detection_technology', sa.String(), nullable=True),
    sa.Column('number_of_buttons', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_mouseattributes_id'), 'mouseattributes', ['id'], unique=False)
    op.create_table('mousepadattributes',
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('special_feature', sa.String(), nullable=True),
    sa.Column('recommended_uses_for_product', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_mousepadattributes_id'), 'mousepadattributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mousepadattributes_id'), table_name='mousepadattributes')
    op.drop_table('mousepadattributes')
    op.drop_index(op.f('ix_mouseattributes_id'), table_name='mouseattributes')
    op.drop_table('mouseattributes')
    op.drop_index(op.f('ix_monitorattributes_id'), table_name='monitorattributes')
    op.drop_table('monitorattributes')
    op.drop_index(op.f('ix_keyboardattributes_id'), table_name='keyboardattributes')
    op.drop_table('keyboardattributes')
    op.drop_index(op.f('ix_headsetattributes_id'), table_name='headsetattributes')
    op.drop_table('headsetattributes')
    op.drop_index(op.f('ix_chairattributes_id'), table_name='chairattributes')
    op.drop_table('chairattributes')
    # ### end Alembic commands ###
