"""update display_name for existing products

Revision ID: update_existing_display_names
Revises: 6613f3102f67
Create Date: 2025-01-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'update_existing_display_names'
down_revision: Union[str, None] = '6613f3102f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update display_name for existing products that don't have it set
    # CPU attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(cpuattributes.brand, ' ', cpuattributes.model)
        FROM cpuattributes 
        WHERE product.id = cpuattributes.product_id 
        AND cpuattributes.brand IS NOT NULL 
        AND cpuattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # CPU Cooler attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(cpucoolerattributes.brand, ' ', cpucoolerattributes.model)
        FROM cpucoolerattributes 
        WHERE product.id = cpucoolerattributes.product_id 
        AND cpucoolerattributes.brand IS NOT NULL 
        AND cpucoolerattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # GPU attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(gpuattributes.brand, ' ', gpuattributes.model)
        FROM gpuattributes 
        WHERE product.id = gpuattributes.product_id 
        AND gpuattributes.brand IS NOT NULL 
        AND gpuattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Motherboard attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(motherboardattributes.brand, ' ', motherboardattributes.model)
        FROM motherboardattributes 
        WHERE product.id = motherboardattributes.product_id 
        AND motherboardattributes.brand IS NOT NULL 
        AND motherboardattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # RAM attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(ramattributes.brand, ' ', ramattributes.model)
        FROM ramattributes 
        WHERE product.id = ramattributes.product_id 
        AND ramattributes.brand IS NOT NULL 
        AND ramattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Storage attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(storageattributes.brand, ' ', storageattributes.model)
        FROM storageattributes 
        WHERE product.id = storageattributes.product_id 
        AND storageattributes.brand IS NOT NULL 
        AND storageattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Power Supply attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(powersupplyattributes.brand, ' ', powersupplyattributes.model)
        FROM powersupplyattributes 
        WHERE product.id = powersupplyattributes.product_id 
        AND powersupplyattributes.brand IS NOT NULL 
        AND powersupplyattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Case attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(caseattributes.brand, ' ', caseattributes.model)
        FROM caseattributes 
        WHERE product.id = caseattributes.product_id 
        AND caseattributes.brand IS NOT NULL 
        AND caseattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Mouse attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(mouseattributes.brand, ' ', mouseattributes.model)
        FROM mouseattributes 
        WHERE product.id = mouseattributes.product_id 
        AND mouseattributes.brand IS NOT NULL 
        AND mouseattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Monitor attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(monitorattributes.brand, ' ', monitorattributes.model)
        FROM monitorattributes 
        WHERE product.id = monitorattributes.product_id 
        AND monitorattributes.brand IS NOT NULL 
        AND monitorattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Keyboard attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(keyboardattributes.brand, ' ', keyboardattributes.model)
        FROM keyboardattributes 
        WHERE product.id = keyboardattributes.product_id 
        AND keyboardattributes.brand IS NOT NULL 
        AND keyboardattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Headset attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(headsetattributes.brand, ' ', headsetattributes.model)
        FROM headsetattributes 
        WHERE product.id = headsetattributes.product_id 
        AND headsetattributes.brand IS NOT NULL 
        AND headsetattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Mousepad attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(mousepadattributes.brand, ' ', mousepadattributes.model)
        FROM mousepadattributes 
        WHERE product.id = mousepadattributes.product_id 
        AND mousepadattributes.brand IS NOT NULL 
        AND mousepadattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # Chair attributes
    op.execute("""
        UPDATE product 
        SET display_name = CONCAT(chairattributes.brand, ' ', chairattributes.model)
        FROM chairattributes 
        WHERE product.id = chairattributes.product_id 
        AND chairattributes.brand IS NOT NULL 
        AND chairattributes.model IS NOT NULL
        AND (product.display_name IS NULL OR product.display_name = '')
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration only updates data, no schema changes to revert
    pass
    # ### end Alembic commands ### 