name: Backend CI/CD


on:
  workflow_dispatch:
  push:
    paths:
      - 'pc-bldr-be-main/**'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_INSTANCE_NAME: ${{ secrets.GCP_INSTANCE_NAME }}
  GCP_INSTANCE_ZONE: ${{ secrets.GCP_INSTANCE_ZONE }}
  IMAGE_NAME: backend
  GCR_REGISTRY: gcr.io

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Auth to GCP
    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Setting GCP SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Auth to GCR
    - name: Docker auth
      run: gcloud auth configure-docker --quiet

    # Build and push image
    - name: Build and push Docker image
      working-directory: ./pc-bldr-be-main
      run: |
        ls
        docker buildx build \       
          --cache-from=type=registry,ref=${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}-cache \
          --cache-to=type=registry,ref=${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}-cache,mode=max \
          -t ${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}  .
          
        docker push ${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # Deploy on instance
    - name: Deploy to GCP instance
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
        KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
      run: |

        FULL_IMAGE_NAME="${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        
        gcloud compute ssh ${{ env.GCP_INSTANCE_NAME }} \
          --zone ${{ env.GCP_INSTANCE_ZONE }} \
          --tunnel-through-iap \
          --command="
            docker pull $FULL_IMAGE_NAME
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker run -d \
              --name ${{ env.IMAGE_NAME }} \
              --restart=always \
              -p 8000:8000 \
              -e POSTGRES_HOST=\"$POSTGRES_HOST\" \
              -e POSTGRES_DSN=\"$ESCAPED_POSTGRES_DSN\" \
              -e KEEPA_API_KEY=\"$ESCAPED_KEEPA_API_KEY\" \
              $FULL_IMAGE_NAME
        PUBLIC_IP=$(gcloud compute instances describe ${{ env.GCP_FRONTEND_INSTANCE_NAME }} \
          --zone=${{ env.GCP_FRONTEND_INSTANCE_ZONE }} \
          --format="get(networkInterfaces[0].accessConfigs[0].natIP)")
    
        echo "ip: $PUBLIC_IP:8000"
