name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - 'pc-bldr-be-main/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_NAME: backend
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Authenticate Docker to AWS ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build and push image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./pc-bldr-be-main/
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy to EC2 instance
    - name: Deploy to AWS EC2
      env:
        POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
        KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
        EC2_HOST: ${{ secrets.EC2_BACKEND_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        SSH_KEY_BASE64: ${{ secrets.EC2_SSH_KEY_BASE64 }}
      run: |
        echo "$SSH_KEY_BASE64" | base64 --decode > ec2_key.pem
        chmod 600 ec2_key.pem
        
        ESCAPED_POSTGRES_DSN=$(echo "$POSTGRES_DSN" | sed 's/"/\\"/g')
        ESCAPED_KEEPA_API_KEY=$(echo "$KEEPA_API_KEY" | sed 's/"/\\"/g')
        FULL_IMAGE_NAME="${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

        ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST <<EOF
          docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_REGISTRY
          docker pull $FULL_IMAGE_NAME
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker image prune -af
          docker run -d --network=backend \
            --name $IMAGE_NAME \
            --restart=always \
            -p 8000:8000 \
            -e POSTGRES_DSN="$ESCAPED_POSTGRES_DSN" \
            -e KEEPA_API_KEY="$ESCAPED_KEEPA_API_KEY" \
            $FULL_IMAGE_NAME
        EOF

        echo "Deployment complete. App running at http://$EC2_HOST:8000"

