name: Backend CI/CD


on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_INSTANCE_NAME: ${{ secrets.GCP_INSTANCE_NAME }}
  GCP_INSTANCE_ZONE: ${{ secrets.GCP_INSTANCE_ZONE }}
  IMAGE_NAME: backend
  GCR_REGISTRY: gcr.io

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Auth to GCP
    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Setting GCP SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Auth to GCR
    - name: Docker auth
      run: gcloud auth configure-docker --quiet

    # Build and push image
    - name: Build and push Docker image
      working-directory: ./pc-bldr-be-main
      run: |
        docker build -t ${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # Deploy on instance
    - name: Deploy to GCP instance
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
        KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
      run: |

        ESCAPED_POSTGRES_DSN=$(echo "$POSTGRES_DSN" | sed 's/"/\\"/g')
        echo "DB Host: $ESCAPED_POSTGRES_DSN"
        ESCAPED_KEEPA_API_KEY=$(echo "$KEEPA_API_KEY" | sed 's/"/\\"/g')
        echo "Database IP: ${{ env.POSTGRES_HOST || secrets.POSTGRES_HOST }}"
        FULL_IMAGE_NAME="${{ env.GCR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        
        gcloud compute ssh ${{ env.GCP_INSTANCE_NAME }} \
          --zone ${{ env.GCP_INSTANCE_ZONE }} \
          --tunnel-through-iap \
          --command="
            docker pull $FULL_IMAGE_NAME
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker run -d \
              --name ${{ env.IMAGE_NAME }} \
              --restart=always \
              -p 8000:8000 \
              -e POSTGRES_HOST=\"$POSTGRES_HOST\" \
              -e POSTGRES_DSN=\"$ESCAPED_POSTGRES_DSN\" \
              -e KEEPA_API_KEY=\"$ESCAPED_KEEPA_API_KEY\" \
              $FULL_IMAGE_NAME
            sleep 5
            docker logs ${{ env.IMAGE_NAME }} --tail 20
          "
